### ISSUE TITLE
Weird Fingers, and also relative rotation of objects in hand (Solution: metacarpal bone chains)

### ISSUE THREAD

**Issue by MacroLP** [tuatec/TTToolbox#33] opened 2023-01-04 10:24 UTC
**Describe the bug**
So upon moving slightly, (transitioning) manny's fingers goes crazy when returning to idle pose.  As well as funky relative Rotation of items in Mannys hand during simulation,  yet when in animation preview using a preview mesh in the socket items seem to be placed fine.

**To Reproduce**

**Expected behavior**

**Screenshots**
https://i.imgur.com/Pvulcw1.png
https://i.imgur.com/5TzXCjN.png
https://i.imgur.com/dYc5SWZ.png

^^ This happens for all items in sockets btw.

Now the weird fingers.
https://i.imgur.com/GnTuHoF.png
https://i.imgur.com/peoAxeH.png

ok even noticed it when returning from ragdoll
https://i.imgur.com/IkAGuDb.png

resting idle seems ok, he returns to this pose https://i.imgur.com/qkkIjuD.png

The funky fingers seems to affect these files here
https://i.imgur.com/2BzbgfN.png

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
Using ALS_Rrefactored.

**Additional context**

I realize your tutorial and the toolbox is meant for regular als and not refactored.  I'd like to use Refactored for ease of use but if I cant fix these hand issues I might have to revert back to regular community als :(

Any help is GREATYLY appreciated. Thank you.

**Comment by AchimTuran** [comment] 2023-01-05 07:54
TTToolbox is not dependend on any locomotion system like ALSv4, ALS Community or ALS Refactored. I just used the base the BP version to show how stuff works. Refactored needs a bit more effort as we have to deal with DataAssets, LinkedAnimLayers and so on.

I think you should check your IK Retargeter, it might have mapped metacarpal* bones/chains. Set them to "None" delete them in the IKRig. Then the finger issues should be gone.

**Comment by MacroLP** [comment] 2023-01-06 06:56
Thank you so fucking much man :) It was the metacarpals for sure.  Now i'm painstakingly trying to keep the neat refactored file hierarchy which is pretty much all I wanted.

**Comment by AchimTuran** [comment] 2023-01-06 08:57
You are welcome! Yeah I sadly stepped into this issue as well some time ago...

Great that it is solved now, pressing my thumbs that your Retargeting journey will still smootly forward.

As the issue is now solved I will close it.

**Closed by AchimTuran** 2023-01-06 08:57 UTC
Labels: bug
